---
title: "Lab 1 Report"
description: "Lab Report for E155 Lab 1"
author: "Natalie Ko"
date: "09/02/2026"
categories:
  - reflection
  - labreport
draft: false
---
## Introduction
In this lab, the E155 development board was assembled and tested to confirm the NUCLEO-32 MCU and UPduino v3.1 FPGA functionality. A design was implemented on the FPGA to control an on-board LED with the on-board high-speed oscillator, as well as control two additional on-board LEDs and an external 7-segment display using combinational logic of switch inputs.

## Design and Testing Methodology

modules etc.

The design was first tested using waveform simulation in QuestaSim


Then, several testbenches were written and run to confirm the outputs of each sub-module and the top-level module in each possible input case. 

Finally, the 7-segment display circuit was built and connected to the FPGA GPIO pins, and the full design was uploaded to the FPGA and deployed on the hardware. The design was tested by toggling the switches to account for all cases and observing the LED and 7-segment display outputs ton confirm functionality.

## Technical Documentation

## Results and Discussion

# Testbench Simulation


## Conclusion
I have spent 24 hours on this lab so far (but some of the hours were trying to debug software issues with Lattice Radiant)

## AI Prototype Summary